# Generated by Django 4.1.2 on 2026-06-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('day', models.CharField(db_index=True, max_length=10)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('dali', models.CharField(max_length=100)),
                ('hex', models.CharField(blank=True, default='', max_length=10)),
                ('multiplier', models.FloatField(default=1)),
                ('components', models.JSONField(default=list)),
                ('total', models.FloatField(default=0)),
            ],
        ),
    ]
