# Generated by Django 4.1.2 on 2026-06-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dali', models.CharField(max_length=100, unique=True)),
                ('hex', models.CharField(blank=True, default='', max_length=10)),
                ('components', models.JSONField(default=list)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated', '-id'],
            },
        ),
    ]
