# Generated by Django 4.1.2 on 2026-06-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0003_import_recipes_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='user',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
