# Generated by Django 4.1.2 on 2026-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0004_productionlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('name_output', models.TextField(blank=True, default='')),
                ('colors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
    ]
