# Generated by Django 4.1.2 on 2026-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0005_imageresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stock', models.FloatField(default=0)),
                ('low_threshold', models.FloatField(default=0)),
            ],
        ),
    ]
