# Generated by Django 4.1.2 on 2026-06-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0006_paintstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintstock',
            name='price_per_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
