# Generated by Django 5.0.14 on 2026-06-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pha", "0008_imageresult_enhanced_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StyleSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=60
                    ),
                ),
                ("sig", models.JSONField(blank=True, default=list)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("user", models.CharField(blank=True, default="", max_length=80)),
            ],
            options={
                "ordering": ["-created_time", "-id"],
            },
        ),
    ]
