# Generated by Django 5.0.14 on 2026-06-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pha", "0009_stylesample"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField(blank=True, default="")),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
