# Generated by Django 4.1.2 on 2026-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0010_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresult',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
