# Generated by Django 4.1.2 on 2026-06-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0011_imageresult_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresult',
            name='design_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
