# Generated by Django 4.2.17 on 2026-06-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0012_imageresult_design_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('colors', models.JSONField(default=list)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PourLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('day', models.CharField(db_index=True, max_length=10)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('painting', models.CharField(max_length=100)),
                ('colors', models.JSONField(default=list)),
                ('color_count', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=1)),
                ('user', models.CharField(blank=True, default='', max_length=80)),
                ('request_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('painting', models.CharField(max_length=100)),
                ('colors', models.JSONField(default=list)),
                ('qty', models.IntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('assignee', models.CharField(blank=True, default='', max_length=80)),
                ('created_by', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('done_by', models.CharField(blank=True, default='', max_length=80)),
                ('done_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', '-created_time', '-id'],
            },
        ),
    ]
