# Generated by Django 4.2.17 on 2026-06-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0013_painting_pourlog_pourrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
