# Generated by Django 4.2.17 on 2026-06-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0014_painting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='color_count',
            field=models.IntegerField(default=0),
        ),
    ]
