# Generated by Django 4.2.17 on 2026-06-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0016_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pourlog',
            name='size',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pourrequest',
            name='size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
