# Generated by Django 4.2.17 on 2026-06-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0017_pourlog_size_pourrequest_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('day', models.CharField(db_index=True, max_length=10)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('painting', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('qty', models.IntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'ordering': ['-created_time', '-id'],
            },
        ),
    ]
