# Generated by Django 4.1.2 on 2026-06-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0018_paintingproduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('source_name', models.TextField()),
                ('enhanced_name', models.TextField(blank=True, default='')),
                ('design_name', models.TextField(blank=True, default='')),
                ('result_name', models.TextField(blank=True, default='')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('sig', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'ordering': ['-created_time', '-id'],
            },
        ),
    ]
