# Generated by Django 4.2.17 on 2026-06-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0019_trainingsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=80)),
                ('day', models.CharField(db_index=True, max_length=10)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('ip_in', models.CharField(blank=True, default='', max_length=64)),
                ('ip_out', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-day', 'user'],
                'unique_together': {('user', 'day')},
            },
        ),
    ]
