# Generated by Django 4.2.17 on 2026-06-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0020_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('bound_time', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_in',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_out',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
