# Generated by Django 4.2.17 on 2026-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0021_devicebind_attendance_device_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('day', models.CharField(db_index=True, max_length=10)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('painting', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.CharField(blank=True, default='', max_length=20)),
                ('qty', models.IntegerField(default=1)),
                ('stage', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('by_user', models.CharField(blank=True, default='', max_length=80)),
                ('reporter', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ['-created_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(db_index=True, max_length=80)),
                ('from_day', models.CharField(db_index=True, max_length=10)),
                ('to_day', models.CharField(db_index=True, max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('decided_by', models.CharField(blank=True, default='', max_length=80)),
                ('decided_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_time', '-id'],
            },
        ),
    ]
