# Generated by Django 4.2.17 on 2026-06-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0022_defectlog_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('image', models.TextField(blank=True, default='')),
                ('w_cm', models.FloatField(default=38)),
                ('h_cm', models.FloatField(default=38)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code', 'w_cm'],
            },
        ),
    ]
