# Generated by Django 4.2.17 on 2026-06-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0023_printart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pdf', models.CharField(max_length=300)),
                ('meters', models.FloatField(default=0)),
                ('util', models.FloatField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('prt_mb', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
        ),
    ]
